services:

  # Certificate Authority
  ca:
    image: keyfactor/ejbca-ce
    hostname: ca
    environment:
      - TLS_SETUP_ENABLED="true"
      - PASSWORD_ENCRYPTION_KEY="foo123"
      - CA_KEYSTOREPASS="foo123"
      - EJBCA_CLI_DEFAULTPASSWORD="foo123"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ca-db:/mnt/persistent

  # Registration Authority
  ra:
    image: keyfactor/ejbca-ce
    hostname: ra
    environment:
      - TLS_SETUP_ENABLED="true"
      - PASSWORD_ENCRYPTION_KEY="foo123"
      - CA_KEYSTOREPASS="foo123"
      - EJBCA_CLI_DEFAULTPASSWORD="foo123"
    ports:
      - "9080:8080"
      - "9443:8443"
    volumes:
      - ra-db:/mnt/persistent

  # Validation Authority
  # va:
  #   image: keyfactor/ejbca-ce
  #   hostname: va
  #   environment:
  #     - TLS_SETUP_ENABLED="true"
  #     - PASSWORD_ENCRYPTION_KEY="foo123"
  #     - CA_KEYSTOREPASS="foo123"
  #     - EJBCA_CLI_DEFAULTPASSWORD="foo123"
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #   volumes:
  #     - va-db:/mnt/persistent

volumes:
  ca-db:
  ra-db:
  # va-db:
